name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  zsh:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: 
        python-version: [3.8]
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      run: |
        sudo apt install zsh
      shell: bash

    - name: Tests
      run: |
        zsh -c "echo hello world"
